
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LLM Generated App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f9f9f9;
                color: #222;
                padding: 40px;
                text-align: center;
            }
            h1 {
                color: #0078D7;
            }
            .footer {
                margin-top: 40px;
                font-size: 14px;
                color: #777;
            }
        </style>
    </head>
    <body>
        <h1>LLM Deployment Demo</h1>
        <p>Prompt received:</p>
        <blockquote>Say hello world</blockquote>
        <p>This is a mock HTML page generated automatically on Render.</p>
        <div class="footer">
            <p>Generated by: <strong>H4D3S21 LLM App Generator</strong></p>
        </div>
    </body>
    </html>
    